project:
  type: website
  output-dir: docs

website:
  title: "Victoria Handford"
  favicon: stars
  announcement:
    icon: info-circle
    dismissable: true
    content: "This website is still under construction."
    type: primary
    position: below-navbar
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: cv.qmd
        text: CV
      - href: projects.qmd
        text: Projects
    right:
      - icon: github
        href: https://github.com/vlhandfo
        aria-label: GitHub


format:
  html:
    theme: journal
    css: styles.css
    toc: true



