project:
  type: website

website:
  title: "Victoria Handford"
  favicon: stars
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: cv.qmd
        text: CV
      - href: projects.qmd
        text: Projects


format:
  html:
    theme: journal
    css: styles.css
    toc: true



